version: "3.7"

services:
    db:
        image: postgres
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=larachat
        ports:
          - "5433:5433"
        volumes:
          - ./docker/postgres-data:/var/lib/postgresql/data
        networks:
            - larachat_network
    app:
        image: larachat
        build:
            context: .
            dockerfile: Dockerfile
        container_name: larachat
        tty: true
        working_dir: /var/www
        volumes: 
            - ./:/var/www
        depends_on:
            - db
        ports:
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
            - '8000:8000'
        networks:
            - larachat_network
    nginx:
        image: nginx:alpine
        container_name: servidor-nginx
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - larachat_network
      
networks:
    larachat_network:
      name: larachat_network
      driver: bridge
  
  

