name: CI

on:
  pull_request:
    brances:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código 
        uses: actions/checkout@v4
      
      - name: Build docker
        run: docker compose build
