name: CI

on:
  pull_request:
    brances:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código 
        uses: actions/checkout@v4
      
      - name: Build docker
        run: docker compose build 

      - name: Levantando containers
        run: docker compose up -d
      
      - name: Composer Install
        run: docker exec larachat composer install
      
      - name: Rodando teste
        run: docker exec larachat composer php artisan test tests/Unit/ExampleTest.php
        