name: CI

on:
  pull_request:
    brances:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código 
        uses: actions/checkout@v4
      
      - name: Build docker
        run: docker compose build 

      - name: Entrando no container
        run: docker exec -it larachat bash

      - name: Composer Install
        run: composer Install
      
      - name:
        run: php artisan test tests/Unit/ExampleTest.php
        