name: CI MAIN
on :
  push:
    branches:
      - main

jobs:
  check_branch: 
    runs-on: ubuntu-latest
    steps:
      - name: Valida branch
        if: github.base_ref == 'main' && github.head_ref != 'staging'
        run: |
          echo "ERRO: Pull requests para a main só são permitidos a partir da branch 'develop'."
          exit 1