name: DEPLOY

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Executando deploy localmente
        run: |
          cd /var/www/larachat
          git checkout main
          git pull